version: "3.6"
services:
  app: 
    image: ghcr.io/foolish15/parking-ticket:main
    ports:
      - 8080:8080
    networks:
      - internal-networks
    environment:
      SERVER_PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: parking
      DB_USERNAME: root
      DB_PASSWORD: secret
  db:
    image: mysql:5.7
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
    ports:
      - 3306:3306
    networks:
      - internal-networks
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: parking
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
networks:
  internal-networks: